# Generated by Django 3.2 on 2023-04-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abo_icon', models.CharField(max_length=60)),
                ('abo_title', models.CharField(max_length=30)),
                ('abo_description', models.TextField()),
                ('abo_order', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=20)),
                ('abo_display', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'About',
                'ordering': ['abo_order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_compagny_name', models.CharField(max_length=30)),
                ('exp_geo', models.CharField(max_length=30)),
                ('exp_poste', models.CharField(default='', max_length=60)),
                ('exp_start', models.DateField()),
                ('exp_stop', models.DateField()),
                ('exp_order', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=20)),
                ('exp_display', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Experience',
                'ordering': ['exp_order'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_title', models.CharField(max_length=30)),
                ('pro_description', models.TextField()),
                ('pro_github', models.CharField(max_length=100, null=True)),
                ('pro_skill', models.CharField(max_length=100, null=True)),
                ('pro_order', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=20)),
                ('pro_display', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Projet',
                'ordering': ['pro_order'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_description', models.CharField(max_length=300, null=True)),
                ('ref_auteur', models.CharField(max_length=100, null=True)),
                ('ref_order', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=20)),
                ('ref_display', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Reference',
                'ordering': ['ref_order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ski_name', models.CharField(max_length=30)),
                ('ski_level', models.IntegerField(default=0)),
                ('ski_order', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=20)),
                ('ski_display', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Skill',
                'ordering': ['ski_order'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_str_date', models.CharField(max_length=30)),
                ('stu_description', models.CharField(max_length=100, null=True)),
                ('stu_organisme', models.CharField(max_length=100, null=True)),
                ('stu_order', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=20)),
                ('stu_display', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Study',
                'ordering': ['stu_order'],
            },
        ),
    ]
